### ISSUE TITLE
squeeze problem

### ISSUE THREAD

**Issue by Ayeliauk** [xuehy/pytorch-maddpg#12]
thank you for your codes
Traceback (most recent call last):
  File "maina.py", line 76, in <module>
    c_loss, a_loss = maddpg.update_policy()
  File "/content/drive/drive/matd3/MADDPG.py", line 117, in update_policy
    self.n_agents * self.n_actions)
AttributeError: 'tuple' object has no attribute 'squeeze'

**Comment by Ayeliauk** [comment]
if I put squeeze  infront，then it occour：
RuntimeError: shape mismatch: value tensor of shape [999, 1] cannot be broadcast to indexing result of shape [999]
